kwik_medical/urls.py
from django.contrib import admin
from django.urls import path, include

import record.urls
import django.contrib.auth.urls

urlpatterns = [
    path('', include(record.urls)),
    path('', include(django.contrib.auth.urls)),
    path('admin/', admin.site.urls),
]

record/urls.py
from django.urls import path

from record.views import overview, incident_form, rescue_request_form, incident_list, medical_record_list, \
    edit_medical_record_form

app_name = "record"

urlpatterns = [
    path('', overview, name='overview'),
    path('incident/', incident_form, name='incident_form'),
    path('list/incident/', incident_list, name='incident_list'),
    path('list/medical_record/', medical_record_list, name='medical_record_list'),
    path('rescue_request/<int:incident_id>', rescue_request_form, name='rescue_request_form'),
    path('medical_record/<int:medical_record_id>', edit_medical_record_form, name='edit_medical_record_form'),
]

record/models.py
from django.db import models

# Create your models here.

record/models/hospital_model.py
from django.db import models


class Hospital(models.Model):
    """
    Model used for the regional hospitals.
    """

    from mapbox_location_field.models import LocationField

    name = models.CharField(max_length=50, blank=True, null=True, verbose_name='Name')
    """The name of the hospital."""

    location = LocationField(null=True, blank=True,
                             map_attrs={"center": [-3.2141745, 55.933486], "marker_color": "blue"},
                             default=[-3.2141745, 55.933486])
    """The location of the hospital."""

    deleted = models.BooleanField(default=False, null=False, verbose_name='Deleted')
    """Is this hospital entry deleted?"""

    class Meta:
        """
        Model Meta is for “anything that’s not a field”, such as ordering options (ordering),
        database table name (db_table), or human-readable singular and plural names.
        """
        db_table = 'Hospital'

    def __str__(self):
        return str(self.name)

record/models/incident_model.py
from django.db import models


class Incident(models.Model):
    """
    Model used for incidents that have occurred.
    """

    from mapbox_location_field.models import LocationField

    nhs_reg_number = models.CharField(max_length=20, blank=False, verbose_name='NHS Registration Number')
    """The NHS registration number of the patient."""

    description = models.CharField(max_length=500, blank=True, null=True, verbose_name='Description')
    """The description of the incident."""

    time_occurred = models.DateTimeField(blank=True, null=True, verbose_name='Time Occurred')
    """The time that the incident occurred."""

    location = LocationField(null=True, blank=True,
                             map_attrs={"center": [-3.2141745, 55.933486], "marker_color": "blue"},
                             default=[-3.2141745, 55.933486])
    """The location of the Incident."""

    action_taken = models.CharField(max_length=50, blank=True, null=True, verbose_name='Action Taken')
    """The action taken for the incident."""

    minutes_on_call = models.IntegerField(null=False, verbose_name='Minutes on Call')
    """The number of minutes the patient was on call."""

    signed_off = models.BooleanField(default=False, null=False, verbose_name='Deleted')
    """Is this incident entry signed off by the hospital?"""

    deleted = models.BooleanField(default=False, null=False, verbose_name='Deleted')
    """Is this incident entry deleted?"""

    class Meta:
        """
        Model Meta is for “anything that’s not a field”, such as ordering options (ordering),
        database table name (db_table), or human-readable singular and plural names.
        """
        db_table = 'Incident'

    def __str__(self):
        return str(self.description)

record/models/medical_record_model.py
from django.db import models


class MedicalRecord(models.Model):
    """
    Model used for the medical records of patients and the associated incidents.
    """

    from record.models.patient_model import Patient
    from record.models.incident_model import Incident

    description = models.CharField(max_length=50, blank=True, null=True, verbose_name='Description')
    """The description of the medical record."""

    treatment = models.CharField(max_length=50, blank=True, null=True, verbose_name='Treatment ')
    """The treatment the patient received."""

    patient = models.ForeignKey(Patient, models.DO_NOTHING, null=False)
    """The ID of the patient."""

    incident = models.ForeignKey(Incident, models.DO_NOTHING, null=True)
    """The ID of the Incident."""

    deleted = models.BooleanField(default=False, null=False, verbose_name='Deleted')
    """Is this incident entry deleted?"""

    class Meta:
        """
        Model Meta is for “anything that’s not a field”, such as ordering options (ordering),
        database table name (db_table), or human-readable singular and plural names.
        """
        db_table = 'MedicalRecord'
        verbose_name_plural = "Medical Records"

    def __str__(self):
        return str(self.description)

record/models/patient_model.py
from django.db import models


class Patient(models.Model):
    """
    Model used for the patients of the NHS.
    """

    nhs_reg_number = models.CharField(max_length=20, blank=False, verbose_name='NHS Registration Number')
    """The NHS registration number of the patient."""

    full_name = models.CharField(max_length=100, blank=False, verbose_name='Full Name')
    """The fullname of the patient."""

    phone_number = models.CharField(max_length=20, null=False, blank=True, verbose_name='Phone Number')
    """The patient's phone number."""

    address = models.CharField(max_length=50, blank=False, verbose_name='Address')
    """The address of the patient."""

    post_code = models.CharField(max_length=10, blank=False, verbose_name='Post Code')
    """The post code of the patient."""

    deleted = models.BooleanField(default=False, null=False, verbose_name='Deleted')
    """Is this patient entry deleted?"""

    class Meta:
        """
        Model Meta is for “anything that’s not a field”, such as ordering options (ordering),
        database table name (db_table), or human-readable singular and plural names.
        """
        db_table = 'Patient'

    def __str__(self):
        return str(self.nhs_reg_number)

record/models/rescue_request_model.py
from django.db import models


class RescueRequest(models.Model):
    """
    Model used for the rescue requests.
    """

    from record.models import Patient
    from record.models.hospital_model import Hospital

    description = models.CharField(max_length=500, blank=True, null=True, verbose_name='Description')
    """The description of the rescue request."""

    patient = models.ForeignKey(Patient, models.DO_NOTHING, null=False)
    """The ID of the patient."""

    hospital = models.ForeignKey(Hospital, models.DO_NOTHING, null=False)
    """The ID of the hospital."""

    deleted = models.BooleanField(default=False, null=False, verbose_name='Deleted')
    """Is this rescue request entry deleted?"""

    class Meta:
        """
        Model Meta is for “anything that’s not a field”, such as ordering options (ordering),
        database table name (db_table), or human-readable singular and plural names.
        """
        db_table = 'RescueRequest'
        verbose_name_plural = "Rescue Requests"

    def __str__(self):
        return str(self.description)

record/forms.py
from django.forms import ModelForm, Textarea, DateTimeField


class PatientForm(ModelForm):
    """
    Form for the Patient table.
    """

    class Meta:
        """
        Model Meta is for “anything that’s not a field”, such as ordering options (ordering),
        database table name (db_table), or human-readable singular and plural names.
        """
        from record.models import Patient
        model = Patient
        fields = '__all__'


class IncidentForm(ModelForm):
    """
    Form for the Incident table.
    """
    from tempus_dominus.widgets import DateTimePicker

    time_occurred = DateTimeField(
        widget=DateTimePicker(
            attrs={
                'input_toggle': True,
                'icon_toggle': False,
                'autocomplete': 'off',
            }
        ),
        label='Date Occurred',
        required=True,
    )

    class Meta:
        """
        Model Meta is for “anything that’s not a field”, such as ordering options (ordering),
        database table name (db_table), or human-readable singular and plural names.
        """
        from record.models import Incident
        model = Incident
        fields = '__all__'

        widgets = {
            'description': Textarea(attrs={'rows': 2}),
            'action_taken': Textarea(attrs={'rows': 2}),
        }


class RescueRequestForm(ModelForm):
    """
    Form for the RescueRequest table.
    """

    class Meta:
        """
        Model Meta is for “anything that’s not a field”, such as ordering options (ordering),
        database table name (db_table), or human-readable singular and plural names.
        """
        from record.models import RescueRequest
        model = RescueRequest
        fields = '__all__'

        widgets = {
            'description': Textarea(attrs={'rows': 2}),
        }


class MedicalRecordForm(ModelForm):
    """
    Form for the MedicalRecord table.
    """

    class Meta:
        """
        Model Meta is for “anything that’s not a field”, such as ordering options (ordering),
        database table name (db_table), or human-readable singular and plural names.
        """
        from record.models import MedicalRecord
        model = MedicalRecord
        fields = '__all__'

        widgets = {
            'description': Textarea(attrs={'rows': 2}),
            'treatment': Textarea(attrs={'rows': 2}),
        }

record/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404


@login_required()
def overview(request):
    """
    Generates and renders the overview screen,
    :param request: The Web Server Gateway Interface request.
    :return: A rendered view of overview screen.
    """

    args = {}
    return render(request, 'record/overview.html', args)


@login_required()
def incident_form(request):
    """
    Generates and renders the Incident form.
    :param request: The Web Server Gateway Interface request.
    :return: A rendered Incident form
    """
    from django.http import HttpResponseRedirect
    from record.forms import IncidentForm, PatientForm
    from record.models import Patient, MedicalRecord

    if request.method == 'POST':
        args = {'incident_form': IncidentForm(request.POST), 'patient_form': PatientForm(request.POST)}
        print(args['incident_form'].errors)

        if args['incident_form'].is_valid() and args['patient_form'].is_valid():
            incident = args['incident_form'].save()

            # Checks if a Patient already exists in the Patient table.
            is_there_a_patient = Patient.objects.filter(nhs_reg_number__exact=incident.nhs_reg_number)

            # If a Patient does not exist, it will create one.
            if not is_there_a_patient:
                args['patient_form'].save()

            patient = get_object_or_404(Patient, nhs_reg_number__icontains=incident.nhs_reg_number)
            medical_record = MedicalRecord(patient=patient, incident=incident)
            medical_record.save()

            return HttpResponseRedirect('/rescue_request/' + str(incident.pk))
    else:
        args = {'incident_form': IncidentForm(), 'patient_form': PatientForm()}

    return render(request, 'record/forms/incident_form.html', args)


@login_required()
def rescue_request_form(request, incident_id: int):
    """
    Generates and renders the Rescue Request form.
    :param incident_id: ID of the Incident.
    :param request: The Web Server Gateway Interface request.
    :return: A rendered Incident form
    """
    from django.http import HttpResponseRedirect
    from record.forms import RescueRequestForm
    from record.models import MedicalRecord, Incident, Patient, Hospital
    from scipy.spatial import KDTree

    if request.method == 'POST':
        redirect = request.POST['redirect']
        args = {'rescue_request_form': RescueRequestForm(request.POST)}
        print(args['rescue_request_form'].errors)
        if args['rescue_request_form'].is_valid():
            args['rescue_request_form'].save()
            return HttpResponseRedirect(redirect)
    else:
        incident = get_object_or_404(Incident, pk=incident_id)

        incident_location = list(incident.location)
        incident_location.reverse()

        hospitals = Hospital.objects.filter(deleted=False).values_list('location', flat=True)
        list_of_hospitals = []

        for hospital in hospitals:
            conv = list(hospital)
            conv.reverse()
            list_of_hospitals.append(conv)

        tree = KDTree(list_of_hospitals)
        closest = tree.query(incident_location)
        list_of_hospitals[closest[1]].reverse()
        closest_converted = tuple(list_of_hospitals[closest[1]])

        closest_hospital = get_object_or_404(Hospital, location=closest_converted)

        patient_exists = Patient.objects.filter(nhs_reg_number__icontains=incident.nhs_reg_number)
        if patient_exists:
            patient = get_object_or_404(Patient, nhs_reg_number__icontains=incident.nhs_reg_number)
            args = {
                'rescue_request_form': RescueRequestForm(initial={'patient': patient, 'hospital': closest_hospital, }),
                'medical_records': MedicalRecord.objects.filter(patient=patient)}

        else:
            args = {'rescue_request_form': RescueRequestForm(initial={'hospital': closest_hospital, }),
                    'medical_records': MedicalRecord.objects.none()}

    return render(request, 'record/forms/rescue_request_form.html', args)


@login_required()
def incident_list(request):
    """
    Generates and renders the incident list.
    :param request: The Web Server Gateway Interface request.
    :return: A rendered list of incidents.
    """
    from django.conf import settings
    from record.models import Incident

    args = {'incident_records': Incident.objects.all().order_by('-pk'),
            'mapbox_access_token': settings.MAPBOX_KEY}

    return render(request, 'record/incident_list.html', args)


@login_required()
def medical_record_list(request):
    """
    Generates and renders the medical record list.
    :param request: The Web Server Gateway Interface request.
    :return: A rendered list of incidents.
    """
    from record.models import MedicalRecord

    args = {'medical_records': MedicalRecord.objects.all().order_by('-pk')}

    return render(request, 'record/medical_record_view.html', args)


def edit_medical_record_form(request, medical_record_id: int):
    """
    Generates and renders the medical record form.
    :param medical_record_id: ID of the MedicalRecord.
    :param request: The Web Server Gateway Interface request.
    :return: A rendered medical record form
    """
    from django.http import HttpResponseRedirect
    from record.forms import MedicalRecordForm
    from record.models import MedicalRecord

    if request.method == 'POST':
        redirect = request.POST['redirect']
        args = {'medical_record_form': MedicalRecordForm(request.POST)}
        print(args['medical_record_form'].errors)

        if args['medical_record_form'].is_valid():
            incident = args['medical_record_form'].save(commit=False)
            incident.pk = medical_record_id
            args['medical_record_form'].save()

            return HttpResponseRedirect(redirect)
    else:
        medical_record = get_object_or_404(MedicalRecord, pk=medical_record_id)
        args = {'medical_record_form': MedicalRecordForm(request.POST or None, instance=medical_record)}

    return render(request, 'record/forms/medical_record_form.html', args)

templates/record/incident_list.html
{% extends 'base.html' %}
{% load static %}

{% load mapbox_location_field_tags %}
{% location_field_includes %}
{% include_jquery %}

{% block head %}
    <script src='{% static 'vendor/mapbox/mapbox-gl.js' %}'></script>
    <link href='{% static 'vendor/mapbox/mapbox-gl.css' %}' rel='stylesheet'/>
{% endblock %}

{% block content %}
    <section class="pb-5 pt-5">
        <div class="container">
            <h1>Incidents</h1>
        </div>
    </section>
    <main class="col-xl-10 m-auto">
        <table class="table table-sm table-bordered border-light rounded-3 text-black table-hover" id="incident_table">
            <thead class="bg-300 cursor-pointer">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">NHS Registration Number</th>
                <th scope="col">Description</th>
                <th scope="col">Time Occurred</th>
                <th scope="col">Action Taken</th>
                <th scope="col">Minutes on Call</th>
            </tr>
            </thead>
            <tbody>
            <script>
                mapboxgl.accessToken = "{{ mapbox_access_token }}";
            </script>
            {% for incident in incident_records %}
                <tr class="table-row cursor-pointer">
                    <th class="col-1" scope="row">{{ incident.id }}</th>
                    <td class="col-1">{{ incident.nhs_reg_number }}</td>
                    <td class="col-3">{{ incident.description }}</td>
                    <td class="col-2">{{ incident.time_occurred }}</td>
                    <td class="col-2">{{ incident.action_taken }}</td>
                    <td class="col-1">{{ incident.minutes_on_call }}</td>
                </tr>
                <tr id='map{{ incident.id }}' width="100%" style='height:400px'></tr>
                <script>
                    let map{{ incident.id }} = new mapboxgl.Map({
                        container: 'map{{ incident.id }}',
                        style: 'mapbox://styles/mapbox/streets-v10',
                        center: [{{ incident.location|first }}, {{ incident.location|last }}],
                        zoom: 12
                    });
                    // Create a default Marker and add it to the map.
                    let marker{{ incident.id }} = new mapboxgl.Marker()
                        .setLngLat([{{ incident.location|first }}, {{ incident.location|last }}])
                        .addTo(map{{ incident.id }});
                </script>
            {% endfor %}
            </tbody>
        </table>
    </main>
{% endblock %}

templates/record/medical_record_list.html
{% load static %}

{% block content %}
    <table class="table table-sm table-bordered border-light rounded-3 text-black table-hover" id="incident_table">
        <thead class="bg-300 cursor-pointer">
        <tr>
            <th scope="col">NHS Registration Number</th>
            <th scope="col">Incident description</th>
            <th scope="col">Description</th>
            <th scope="col">Treatment</th>
            <th scope="col">Edit</th>
        </tr>
        </thead>
        <tbody>
        {% for medical_record in medical_records %}
            {% if medical_record.description == None or medical_record.treatment == None  %}
                <tr class="table-row cursor-pointer">
                    <td class="col-1 text-danger">{{ medical_record.patient.nhs_reg_number }}</td>
                    <td class="col-2 text-danger">{{ medical_record.incident.description }}</td>
                    <td class="col-1 text-danger">{{ medical_record.description }}</td>
                    <td class="col-2 text-danger">{{ medical_record.treatment }}</td>
                    <td class="text-center col-1">
                        <a class="btn btn-sm btn-primary"
                           href="{% url 'record:edit_medical_record_form' medical_record.pk %}"
                           role="button">
                            <i class="fas fa-edit"></i>
                        </a>
                    </td>
                </tr>
            {% else %}
                <tr class="table-row cursor-pointer">
                    <td class="col-1">{{ medical_record.patient.nhs_reg_number }}</td>
                    <td class="col-2">{{ medical_record.incident.description }}</td>
                    <td class="col-1">{{ medical_record.description }}</td>
                    <td class="col-2">{{ medical_record.treatment }}</td>
                    <td class="text-center col-1">
                        <a class="btn btn-sm btn-primary"
                           href="{% url 'record:edit_medical_record_form' medical_record.pk %}"
                           role="button">
                            <i class="fas fa-edit"></i>
                        </a>
                    </td>
                </tr>
            {% endif %}
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/record/medical_record_view.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="pb-5 pt-5">
        <div class="container">
            <h1>Medical Records</h1>
        </div>
    </section>
    <main class="col-xl-10 m-auto">
        <div class="row mb-2">
            <p>
                <strong>
                    Entries marked in red required attention.
                </strong>
            </p>
        </div>
        {% include 'record/medical_record_list.html' %}
    </main>
{% endblock %}

templates/record/overview.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <section class="pb-5 pt-5">
        <div class="container d-flex">
            <h1>Home</h1>
        </div>
    </section>
    <main class="col-xl-10 m-auto">
        {% if user.username != 'hospital' %}
            <div class="row">
            {% if user.username != 'ambulance' %}
                <div class="col-sm-6 col-lg-6 mb-4">
                    <div class="card text-white bg-secondary">
                        <div class="card-body">
                            <div class="card-title">New Incident</div>
                            <p class="card-text">Report a new incident that has occurred.</p>
                            <div class="d-grid gap-2">
                                <a role="button" class="btn btn-block btn-primary"
                                   href="{% url 'record:incident_form' %}">Enter</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
            <div class="col-sm-6 col-lg-6 mb-4">
                <div class="card text-white bg-secondary">
                    <div class="card-body">
                        <div class="card-title">Incidents</div>
                        <p class="card-text">A list of all the Incidents.</p>
                        <div class="d-grid gap-2">
                            <a role="button" class="btn btn-block btn-primary" href="{% url 'record:incident_list' %}">Enter</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
        {% if user.username != 'operator' %}
            {% if user.username != 'ambulance' %}
                <div class="col-sm-6 col-lg-6 mb-4">
                    <div class="card text-white bg-secondary">
                        <div class="card-body">
                            <div class="card-title">Medical Records</div>
                            <p class="card-text">A list of all the Medical Records.</p>
                            <div class="d-grid gap-2">
                                <a role="button" class="btn btn-block btn-primary"
                                   href="{% url 'record:medical_record_list' %}">Enter</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endif %}
        </div>
    </main>

{% endblock %}