kwik_medical/urls.py
from django.contrib import admin
from django.urls import path, include

import record.urls
import django.contrib.auth.urls

urlpatterns = [
    path('', include(record.urls)),
    path('', include(django.contrib.auth.urls)),
    path('admin/', admin.site.urls),
]

record/urls.py
from django.urls import path

from record.views import overview, incident_form, rescue_request_form, incident_list, medical_record_list, \
    edit_medical_record_form

app_name = "record"

urlpatterns = [
    path('', overview, name='overview'),
    path('incident/', incident_form, name='incident_form'),
    path('list/incident/', incident_list, name='incident_list'),
    path('list/medical_record/', medical_record_list, name='medical_record_list'),
    path('rescue_request/<int:incident_id>', rescue_request_form, name='rescue_request_form'),
    path('medical_record/<int:medical_record_id>', edit_medical_record_form, name='edit_medical_record_form'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>KwikMedical</title>

    {#    <link rel="shortcut icon" href="{% static 'base/file/Userfy Logo.png' %}"/>#}

    <link href="{% static 'vendor/bootstrap-5.3.1/css/bootstrap.min.css' %}" rel="stylesheet"/>

    <!-- Our project just needs Font Awesome Free's Solid and Brand files -->
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">

    {% load mapbox_location_field_tags %}
    {% location_field_includes %}
    {% include_jquery %}

    {% block head %}
    {% endblock %}

</head>
<body>

{% include 'navbar.html' %}

{% block content %}
{% endblock %}

{% block footer %}
{% endblock %}

<script type="text/javascript" src="{% static "vendor/jquery-3.6.3.min.js" %}"></script>
<script type="text/javascript" src="{% static "vendor/jquery-3.6.3.js" %}"></script>
<script type="text/javascript" src="{% static "vendor/bootstrap-5.3.1/js/bootstrap.min.js" %}"></script>
<script type="text/javascript" src="{% static "vendor/bootstrap-5.3.1/js/bootstrap.bundle.js" %}"></script>

</body>
</html>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-light navbar-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'record:overview' %}">
            <i class="fa-solid fa-truck-medical"></i>
            KwikMedical
        </a>
        {% if user.is_authenticated %}
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#kwikMedicalNavbar"
                    aria-controls="kwikMedicalNavbar" aria-expanded="false" aria-label="Toggle navigation"><span
                    class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse justify-content-between" id="kwikMedicalNavbar">

                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'record:overview' %}">Home</a>
                    </li>
                    {% if user.username != 'hospital' %}
                        {% if user.username != 'ambulance' %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'record:incident_form' %}">New Incident</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'record:incident_list' %}">Incidents</a>
                        </li>
                    {% endif %}
                    {% if user.username != 'operator' %}
                        {% if user.username != 'ambulance' %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'record:medical_record_list' %}">Medical Records</a>
                            </li>
                        {% endif %}
                    {% endif %}
                </ul>
                <ul class="navbar-nav ml-5">
                    <!-- Nav Item - User Information -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            {{ user.get_full_name }}
                            <i class="fas fa-user-alt"></i>
                        </a>
                        <!-- Dropdown - User Information -->
                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                            {% if user.is_superuser %}
                                <a class="dropdown-item" target="_blank" href="{% url 'admin:index' %}">
                                    <i class="fas fa-users-cog fa-sm fa-fw mr-2"></i>Admin
                                </a>
                            {% endif %}
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'logout' %}">
                                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2"></i>Logout
                            </a>
                        </div>
                    </li>
                </ul>
            </div>
        {% endif %}
    </div>
</nav>